service: daddy-joke-telegram-bot # NOTE: update this with your service name

provider:
  name: aws
  runtime: python2.7
  environment:
    TELEGRAM_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, ''}

functions:
  webhook:
    handler: handler.webhook
    events:
      - http: POST /

  set_webhook:
    handler: handler.set_webhook
    events:
      - http: POST /set_webhook

  get_webhook_info:
    handler: handler.get_webhook_info
    events:
      - http: POST /get_webhook_info

plugins:
  - serverless-python-requirements
